export const CITIES_EN = {
  "Slovenia": ["Ljubljana", "Maribor", "Celje", "Kranj", "Velenje", "Koper", "Novo Mesto", "Ptuj", "Kamnik", "Jesenice", "Nova Gorica", "DomÅ¾ale", "Å kofja Loka", "Postojna", "Murska Sobota", "Mozirje", "Other"],
  "Croatia": ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Pula", "Karlovac", "VaraÅ¾din", "Å ibenik", "Dubrovnik", "Other"],
  "Serbia": ["Belgrade", "Novi Sad", "NiÅ¡", "Kragujevac", "Subotica", "Zrenjanin", "PanÄevo", "ÄŒaÄak", "KruÅ¡evac", "Other"],
  "Bosnia and Herzegovina": ["Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar", "Prijedor", "BrÄko", "Bijeljina", "Other"],
  "North Macedonia": ["Skopje", "Bitola", "Kumanovo", "Prilep", "Tetovo", "Veles", "Ohrid", "Gostivar", "Other"],
  "Montenegro": ["Podgorica", "NikÅ¡iÄ‡", "Pljevlja", "Bijelo Polje", "Cetinje", "Bar", "Herceg Novi", "Budva", "Other"],
  "Austria": ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck", "Klagenfurt", "Villach", "Wels", "Other"],
  "Germany": ["Berlin", "Munich", "Frankfurt", "Hamburg", "Cologne", "Stuttgart", "DÃ¼sseldorf", "Leipzig", "Other"],
  "Italy": ["Rome", "Milan", "Turin", "Naples", "Genoa", "Bologna", "Florence", "Venice", "Trieste", "Other"],
  "Switzerland": ["Zurich", "Geneva", "Basel", "Bern", "Lausanne", "Lucerne", "Other"],
  "United Kingdom": ["London", "Manchester", "Birmingham", "Liverpool", "Leeds", "Glasgow", "Edinburgh", "Other"],
  "France": ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Bordeaux", "Other"],
  "Spain": ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza", "Malaga", "Bilbao", "Other"],
  "Portugal": ["Lisbon", "Porto", "Braga", "Coimbra", "Faro", "Other"],
  "Netherlands": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Tilburg", "Other"],
  "Belgium": ["Brussels", "Antwerp", "Ghent", "Charleroi", "LiÃ¨ge", "Bruges", "Other"],
  "Denmark": ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg", "Other"],
  "Sweden": ["Stockholm", "Gothenburg", "MalmÃ¶", "Uppsala", "VÃ¤sterÃ¥s", "Ã–rebro", "Other"],
  "Norway": ["Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen", "Other"],
  "Finland": ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku", "Other"],
  "Poland": ["Warsaw", "Krakow", "Lodz", "Wroclaw", "Poznan", "Gdansk", "Other"],
  "Czech Republic": ["Prague", "Brno", "Ostrava", "Plzen", "Liberec", "Other"],
  "Slovakia": ["Bratislava", "Kosice", "Presov", "Zilina", "Banska Bystrica", "Other"],
  "Hungary": ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pecs", "Gyor", "Other"],
  "Romania": ["Bucharest", "Cluj-Napoca", "Timisoara", "Iasi", "Constanta", "Other"],
  "Bulgaria": ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse", "Other"],
  "Greece": ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa", "Other"],
  "United States": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose", "Other"],
  "Canada": ["Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton", "Ottawa", "Winnipeg", "Other"],
  "Australia": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast", "Canberra", "Other"],
  "New Zealand": ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga", "Other"]
};

export const CITIES_BY_COUNTRY = {
  "Slovenija": ["Ljubljana", "Maribor", "Celje", "Kranj", "Velenje", "Koper", "Novo mesto", "Ptuj", "Kamnik", "Jesenice", "Nova Gorica", "DomÅ¾ale", "Å kofja Loka", "Postojna", "Murska Sobota", "Mozirje", "Drugo"],
  "HrvaÅ¡ka": ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Pula", "Karlovac", "VaraÅ¾din", "Å ibenik", "Dubrovnik", "Drugo"],
  "Srbija": ["Beograd", "Novi Sad", "NiÅ¡", "Kragujevac", "Subotica", "Zrenjanin", "PanÄevo", "ÄŒaÄak", "KruÅ¡evac", "Drugo"],
  "Bosna in Hercegovina": ["Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar", "Prijedor", "BrÄko", "Bijeljina", "Drugo"],
  "Makedonija": ["Skopje", "Bitola", "Kumanovo", "Prilep", "Tetovo", "Veles", "Ohrid", "Gostivar", "Drugo"],
  "ÄŒrna gora": ["Podgorica", "NikÅ¡iÄ‡", "Pljevlja", "Bijelo Polje", "Cetinje", "Bar", "Herceg Novi", "Budva", "Drugo"],
  "Avstrija": ["Dunaj", "Gradec", "Linz", "Salzburg", "Innsbruck", "Klagenfurt", "Villach", "Wels", "Drugo"],
  "NemÄija": ["Berlin", "MÃ¼nchen", "Frankfurt", "Hamburg", "KÃ¶ln", "Stuttgart", "DÃ¼sseldorf", "Leipzig", "Drugo"],
  "Italija": ["Rim", "Milano", "Torino", "Neapelj", "Genova", "Bologna", "Firenca", "Benetke", "Trst", "Drugo"],
  "Å vica": ["ZÃ¼rich", "Å½eneva", "Basel", "Bern", "Lausanne", "Luzern", "Drugo"],
  "Velika Britanija": ["London", "Manchester", "Birmingham", "Liverpool", "Leeds", "Glasgow", "Edinburgh", "Drugo"],
  "Francija": ["Pariz", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Bordeaux", "Drugo"],
  "Å panija": ["Madrid", "Barcelona", "Valencia", "Sevilla", "Zaragoza", "MÃ¡laga", "Bilbao", "Drugo"],
  "Portugalska": ["Lizbona", "Porto", "Braga", "Coimbra", "Faro", "Drugo"],
  "Nizozemska": ["Amsterdam", "Rotterdam", "Haag", "Utrecht", "Eindhoven", "Tilburg", "Drugo"],
  "Belgija": ["Bruselj", "Antwerpen", "Gent", "Charleroi", "LiÃ¨ge", "Brugge", "Drugo"],
  "Danska": ["KÃ¸benhavn", "Aarhus", "Odense", "Aalborg", "Esbjerg", "Drugo"],
  "Å vedska": ["Stockholm", "GÃ¶teborg", "MalmÃ¶", "Uppsala", "VÃ¤sterÃ¥s", "Ã–rebro", "Drugo"],
  "NorveÅ¡ka": ["Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen", "Drugo"],
  "Finska": ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku", "Drugo"],
  "Poljska": ["VarÅ¡ava", "Krakov", "ÅÃ³dÅº", "WrocÅ‚aw", "PoznaÅ„", "GdaÅ„sk", "Drugo"],
  "ÄŒeÅ¡ka": ["Praga", "Brno", "Ostrava", "PlzeÅˆ", "Liberec", "Drugo"],
  "SlovaÅ¡ka": ["Bratislava", "KoÅ¡ice", "PreÅ¡ov", "Å½ilina", "BanskÃ¡ Bystrica", "Drugo"],
  "MadÅ¾arska": ["BudimpeÅ¡ta", "Debrecen", "Szeged", "Miskolc", "PÃ©cs", "GyÅ‘r", "Drugo"],
  "Romunija": ["BukareÅ¡ta", "Cluj-Napoca", "TimiÈ™oara", "IaÈ™i", "ConstanÈ›a", "Drugo"],
  "Bolgarija": ["Sofija", "Plovdiv", "Varna", "Burgas", "Ruse", "Drugo"],
  "GrÄija": ["Atene", "Solun", "Patra", "Iraklio", "Larisa", "Drugo"],
  "ZDA": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose", "Drugo"],
  "Kanada": ["Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton", "Ottawa", "Winnipeg", "Drugo"],
  "Avstralija": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast", "Canberra", "Drugo"],
  "Nova Zelandija": ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga", "Drugo"]
};
